FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

# Serve using an HTTP server like serve
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "3000"]
